Clarify how to update iai-callgrind-runner.
Joining7943/iai-callgrind pull request #22
Opened 2023-09-28 11:48 UTC by nihohit

2023-09-29 06:32 UTC, Joining7943 commented
Thanks for contributing! The pr looks good. It just needs a few corrections.

2023-09-29 08:44 UTC, nihohit commented
@Joining7943. What are the corrections?

2023-09-29 14:18 UTC, Joining7943 commented
@nihohit See the review for the lines which need correction. Maybe something like `Please update iai-callgrind to '{}' in your Cargo.toml file`

2023-09-29 14:22 UTC, nihohit commented
Sorry, I don't see the review comments - maybe you didn't post it?

2023-09-29 15:45 UTC, Joining7943 requested changes

2023-09-29 15:46 UTC, Joining7943 commented
yeah. Forgot to submit the reviews. Hope you see them now

2023-09-30 16:45 UTC, Joining7943 commented
Looks good now! There's just a small formatting issue left. This repo uses `cargo +nightly fmt` for formatting (and just for the formatting).

2023-09-30 17:16 UTC, Joining7943 requested changes
Please don't resolve reviews. I'll resolve them, when everything's alright.

2023-09-30 17:16 UTC, Joining7943 commented on iai-callgrind-runner/src/main.rs
> +                             update iai-callgrind to '{1}' in your Cargo.toml file",
iai-callgrind needs to be updated to the newer runner version, which is `{0}`. So, this needs to be `... update iai-callgrind to '{0}' in your ...`

2023-10-01 04:59 UTC, Joining7943 commented on iai-callgrind-runner/src/main.rs
> +                             update iai-callgrind to '{1}' in your Cargo.toml file",
Thanks :)

2023-10-01 05:03 UTC, merged